import { IProduct } from "@/types";
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<IProduct>
) {
  res.send("Okkkkkk");
}

[
  {
    image: "/products/cpu1.jpg",
    productName: "CPU 1",
    type: "cpu",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 399.99,
    rating: 4.7,
    description: "High-performance CPU for gaming and productivity tasks.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedMaster-5000",
      specification: "Intel Core i9-9900K, 8 cores, 16 threads",
      port: "Socket LGA1200",
      type: "Desktop CPU",
      voltage: "110-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.8,
    reviews: [
      {
        username: "user1",
        rating: 5,
        comment: "This CPU is a beast! It handles everything I throw at it.",
      },
      {
        username: "user2",
        rating: 4,
        comment: "Great CPU, but it runs a bit hot under heavy load.",
      },
    ],
  },
  {
    image: "/products/ram1.jpg",
    productName: "RAM 1",
    type: "ram",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 129.99,
    rating: 4.5,
    description: "High-speed RAM for smooth multitasking and gaming.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedBoost-16GB",
      specification: "16GB DDR4, 3200MHz",
      port: "DIMM",
      type: "Desktop RAM",
      voltage: "1.35V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user3",
        rating: 5,
        comment: "Amazing RAM! My system feels super fast now.",
      },
      {
        username: "user4",
        rating: 4,
        comment: "Good RAM, but I wish it had RGB lighting.",
      },
    ],
  },
  {
    image: "/products/motherboard1.jpg",
    productName: "Motherboard 1",
    type: "motherboard",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 199.99,
    rating: 4.6,
    description: "Feature-rich motherboard for building a powerful PC.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoard-Z590",
      specification: "ATX, Socket LGA1200, DDR4, USB 3.2 Gen 2, Wi-Fi 6",
      port: "Multiple expansion slots",
      type: "Desktop Motherboard",
      voltage: "12V",
    },
    individualRating: 4.8,
    averageRating: 4.7,
    reviews: [
      {
        username: "user5",
        rating: 5,
        comment:
          "Great motherboard with plenty of features. Highly recommended.",
      },
      {
        username: "user6",
        rating: 4,
        comment: "Solid motherboard, but the BIOS interface could be better.",
      },
    ],
  },
  {
    image: "/products/monitor1.png",
    productName: "Monitor 1",
    type: "monitor",
    category: "Electronics > Computers > Monitors",
    status: "Out of Stock",
    price: 299.99,
    rating: 4.8,
    description: "High-quality monitor for gaming and professional work.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "VisionMaster-27",
      specification: "27-inch, 1440p, 144Hz, IPS panel",
      port: "HDMI, DisplayPort",
      type: "Gaming Monitor",
      resolution: "2560x1440 (QHD)",
      voltage: "100-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.9,
    reviews: [
      {
        username: "user7",
        rating: 5,
        comment: "Best monitor I've ever used. The colors are stunning!",
      },
      {
        username: "user8",
        rating: 5,
        comment:
          "High refresh rate and excellent image quality. Perfect for gaming.",
      },
    ],
  },
  {
    image: "/products/power-supply1.jpg",
    productName: "Power Supply 1",
    type: "power-supply",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 89.99,
    rating: 4.3,
    description: "Reliable power supply with high efficiency.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoost-750",
      specification: "750W, 80+ Gold Certified, Fully Modular",
      port: "Multiple connectors",
      type: "ATX Power Supply",
      voltage: "100-240V AC",
    },
    individualRating: 4.5,
    averageRating: 4.4,
    reviews: [
      {
        username: "user9",
        rating: 4,
        comment: "Works well, but the cables are a bit stiff to manage.",
      },
      {
        username: "user10",
        rating: 4,
        comment: "Decent power supply, no issues so far.",
      },
    ],
  },
  {
    image: "/products/storage1.jpg",
    productName: "Storage Device 1",
    type: "storage",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 149.99,
    rating: 4.6,
    description: "High-speed storage device for faster data access.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedDrive-1TB",
      specification: "1TB NVMe M.2 SSD",
      port: "M.2",
      type: "Internal SSD",
      voltage: "12V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user11",
        rating: 5,
        comment: "Super fast SSD! My system boots up in seconds.",
      },
      {
        username: "user12",
        rating: 4,
        comment: "Good SSD, but the capacity is a bit limiting.",
      },
    ],
  },
  {
    image: "/products/cpu2.jpg",
    productName: "CPU 2",
    type: "cpu",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 399.99,
    rating: 4.7,
    description: "High-performance CPU for gaming and productivity tasks.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedMaster-6000",
      specification: "Intel Core i7-11700K, 8 cores, 16 threads",
      port: "Socket LGA1200",
      type: "Desktop CPU",
      voltage: "110-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.8,
    reviews: [
      {
        username: "user13",
        rating: 5,
        comment: "This CPU is fantastic! It runs all my applications smoothly.",
      },
      {
        username: "user14",
        rating: 4,
        comment: "Great value for money, but the stock cooler could be better.",
      },
    ],
  },
  {
    image: "/products/ram2.webp",
    productName: "RAM 2",
    type: "ram",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 129.99,
    rating: 4.5,
    description: "High-speed RAM for smooth multitasking and gaming.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedBoost-32GB",
      specification: "32GB DDR4, 3600MHz",
      port: "DIMM",
      type: "Desktop RAM",
      voltage: "1.35V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user15",
        rating: 5,
        comment: "Top-notch RAM! My applications load in a blink of an eye.",
      },
      {
        username: "user16",
        rating: 4,
        comment: "Excellent RAM, but it's a bit pricey.",
      },
    ],
  },
  {
    image: "/products/motherboard2.jpg",
    productName: "Motherboard 2",
    type: "motherboard",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 199.99,
    rating: 4.6,
    description: "Feature-rich motherboard for building a powerful PC.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoard-B560",
      specification: "ATX, Socket LGA1200, DDR4, USB 3.2 Gen 2, Wi-Fi 6",
      port: "Multiple expansion slots",
      type: "Desktop Motherboard",
      voltage: "12V",
    },
    individualRating: 4.8,
    averageRating: 4.7,
    reviews: [
      {
        username: "user17",
        rating: 5,
        comment: "Superb motherboard! It has everything I need for my build.",
      },
      {
        username: "user18",
        rating: 4,
        comment: "Great quality, but the BIOS could be more user-friendly.",
      },
    ],
  },
  {
    image: "/products/monitor2.jpg",
    productName: "Monitor 2",
    type: "monitor",
    category: "Electronics > Computers > Monitors",
    status: "Out of Stock",
    price: 299.99,
    rating: 4.8,
    description: "High-quality monitor for gaming and professional work.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "VisionMaster-32",
      specification: "32-inch, 4K, 60Hz, IPS panel",
      port: "HDMI, DisplayPort",
      type: "4K Monitor",
      resolution: "3840x2160 (4K UHD)",
      voltage: "100-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.9,
    reviews: [
      {
        username: "user19",
        rating: 5,
        comment: "Excellent 4K monitor! It's perfect for photo editing.",
      },
      {
        username: "user20",
        rating: 5,
        comment: "Impressive colors and sharpness. Great for gaming too.",
      },
    ],
  },
  {
    image: "/products/power-supply2.jpg",
    productName: "Power Supply 2",
    type: "power-supply",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 89.99,
    rating: 4.3,
    description: "Reliable power supply with high efficiency.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoost-850",
      specification: "850W, 80+ Gold Certified, Fully Modular",
      port: "Multiple connectors",
      type: "ATX Power Supply",
      voltage: "100-240V AC",
    },
    individualRating: 4.5,
    averageRating: 4.4,
    reviews: [
      {
        username: "user21",
        rating: 4,
        comment: "Solid power supply, but it could use more PCIe connectors.",
      },
      {
        username: "user22",
        rating: 4,
        comment: "Reliable performance, no complaints so far.",
      },
    ],
  },
  {
    image: "/products/storage2.jpg",
    productName: "Storage Device 2",
    type: "storage",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 149.99,
    rating: 4.6,
    description: "High-speed storage device for faster data access.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedDrive-2TB",
      specification: "2TB NVMe M.2 SSD",
      port: "M.2",
      type: "Internal SSD",
      voltage: "12V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user23",
        rating: 5,
        comment: "Lightning-fast SSD! My applications launch instantly.",
      },
      {
        username: "user24",
        rating: 4,
        comment: "Great SSD, but it's a bit expensive for the capacity.",
      },
    ],
  },
  {
    image: "/products/cpu3.jpg",
    productName: "CPU 3",
    type: "cpu",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 399.99,
    rating: 4.7,
    description: "High-performance CPU for gaming and productivity tasks.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedMaster-7000",
      specification: "AMD Ryzen 9 5900X, 12 cores, 24 threads",
      port: "Socket AM4",
      type: "Desktop CPU",
      voltage: "110-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.8,
    reviews: [
      {
        username: "user25",
        rating: 5,
        comment: "This CPU is a monster! Handles heavy workloads like a champ.",
      },
      {
        username: "user26",
        rating: 4,
        comment: "Excellent CPU, but I wish it had a better stock cooler.",
      },
    ],
  },
  {
    image: "/products/ram3.webp",
    productName: "RAM 3",
    type: "ram",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 129.99,
    rating: 4.5,
    description: "High-speed RAM for smooth multitasking and gaming.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedBoost-64GB",
      specification: "64GB DDR4, 3600MHz",
      port: "DIMM",
      type: "Desktop RAM",
      voltage: "1.35V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user27",
        rating: 5,
        comment: "Outstanding RAM! My virtual machines run like a breeze.",
      },
      {
        username: "user28",
        rating: 4,
        comment: "Great performance, but it's a bit expensive.",
      },
    ],
  },
  {
    image: "/products/motherboard3.jpg",
    productName: "Motherboard 3",
    type: "motherboard",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 199.99,
    rating: 4.6,
    description: "Feature-rich motherboard for building a powerful PC.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoard-X570",
      specification: "ATX, Socket AM4, DDR4, USB 3.2 Gen 2, Wi-Fi 6",
      port: "Multiple expansion slots",
      type: "Desktop Motherboard",
      voltage: "12V",
    },
    individualRating: 4.8,
    averageRating: 4.7,
    reviews: [
      {
        username: "user29",
        rating: 5,
        comment: "Fantastic motherboard! It has all the latest features.",
      },
      {
        username: "user30",
        rating: 4,
        comment: "Great build quality, but the BIOS could be more intuitive.",
      },
    ],
  },
  {
    image: "/products/monitor3.jpg",
    productName: "Monitor 3",
    type: "monitor",
    category: "Electronics > Computers > Monitors",
    status: "Out of Stock",
    price: 299.99,
    rating: 4.8,
    description: "High-quality monitor for gaming and professional work.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "VisionMaster-24",
      specification: "24-inch, 1080p, 144Hz, TN panel",
      port: "HDMI, DisplayPort",
      type: "Gaming Monitor",
      resolution: "1920x1080 (Full HD)",
      voltage: "100-240V AC",
    },
    individualRating: 4.9,
    averageRating: 4.9,
    reviews: [
      {
        username: "user31",
        rating: 5,
        comment:
          "Excellent gaming monitor! The high refresh rate is a game-changer.",
      },
      {
        username: "user32",
        rating: 5,
        comment:
          "Smooth performance and responsive. Great for competitive gaming.",
      },
    ],
  },
  {
    image: "/products/power-supply3.webp",
    productName: "Power Supply 3",
    type: "power-supply",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 89.99,
    rating: 4.3,
    description: "Reliable power supply with high efficiency.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "PowerBoost-1000",
      specification: "1000W, 80+ Gold Certified, Fully Modular",
      port: "Multiple connectors",
      type: "ATX Power Supply",
      voltage: "100-240V AC",
    },
    individualRating: 4.5,
    averageRating: 4.4,
    reviews: [
      {
        username: "user33",
        rating: 4,
        comment:
          "Powerful power supply, but the fan can get a bit loud under load.",
      },
      {
        username: "user34",
        rating: 4,
        comment: "Stable performance, no complaints so far.",
      },
    ],
  },
  {
    image: "/products/storage3.png",
    productName: "Storage Device 3",
    type: "storage",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 149.99,
    rating: 4.6,
    description: "High-speed storage device for faster data access.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedDrive-4TB",
      specification: "4TB NVMe M.2 SSD",
      port: "M.2",
      type: "Internal SSD",
      voltage: "12V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user35",
        rating: 5,
        comment: "Outstanding SSD! My applications launch almost instantly.",
      },
      {
        username: "user36",
        rating: 4,
        comment: "Good SSD, but it's a bit pricey for the capacity.",
      },
    ],
  },
  {
    image: "/products/others.png",
    productName: "Others Device 3",
    type: "others",
    category: "Electronics > Computers > Components",
    status: "In Stock",
    price: 149.99,
    rating: 4.6,
    description: "High-speed storage device for faster data access.",
    keyFeatures: {
      brand: "ExampleTech",
      model: "SpeedDrive-4TB",
      specification: "4TB NVMe M.2 SSD",
      port: "M.2",
      type: "Internal SSD",
      voltage: "12V",
    },
    individualRating: 4.7,
    averageRating: 4.6,
    reviews: [
      {
        username: "user35",
        rating: 5,
        comment: "Outstanding SSD! My applications launch almost instantly.",
      },
      {
        username: "user36",
        rating: 4,
        comment: "Good SSD, but it's a bit pricey for the capacity.",
      },
    ],
  },
];
